INSERT INTO ticket (date_time, row_number, seat_number, movie_cinema_id, user_account_id) VALUES
                                                                                              ('2020-12-05 20:00:00', 14, 15, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 1 - EMPIRE') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Gentleman') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'josie_story@email.com')),
                   ('2020-12-05 20:00:00', 18, 7, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 1 - EMPIRE') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Gentleman') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'bernard@email.com')),
                   ('2020-12-05 20:00:00', 9, 9, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 1 - EMPIRE') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Gentleman') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'faith.p@email.com')),
                   ('2020-12-05 20:00:00', 12, 18, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 1 - EMPIRE') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Gentleman') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'johnnie@email.com')),
                   ('2020-12-05 20:00:00', 11, 5, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 1 - EMPIRE') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Gentleman') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'lawrence.f@email.com')),

                   ('2020-12-06 20:45:00', 14, 15, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 4 - SQUARE 13') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'Tenet') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'josie_story@email.com')),
                   ('2020-12-06 20:45:00', 18, 7, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 4 - SQUARE 13') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'Tenet') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'bernard@email.com')),
                   ('2020-12-06 20:45:00', 9, 9, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 4 - SQUARE 13') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'Tenet') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'faith.p@email.com')),
                   ('2020-12-06 20:45:00', 12, 18, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 4 - SQUARE 13') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'Tenet') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'johnnie@email.com')),
                   ('2020-12-06 20:45:00', 11, 5, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 4 - SQUARE 13') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'Tenet') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'lawrence.f@email.com')),

                   ('2020-12-07 21:30:00', 14, 15, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 2 - VILLAGE 7') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Nights Before Christmas') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'josie_story@email.com')),
                   ('2020-12-07 21:30:00', 18, 7, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 2 - VILLAGE 7') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Nights Before Christmas') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'bernard@email.com')),
                   ('2020-12-07 21:30:00', 9, 9, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 2 - VILLAGE 7') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Nights Before Christmas') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'faith.p@email.com')),
                   ('2020-12-07 21:30:00', 12, 18, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 2 - VILLAGE 7') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Nights Before Christmas') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'johnnie@email.com')),
                   ('2020-12-07 21:30:00', 11, 5, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 2 - VILLAGE 7') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Nights Before Christmas') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'lawrence.f@email.com')),

                   ('2020-12-08 19:00:00', 14, 15, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 3 - STREET 14') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Shawshank Redemption') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'josie_story@email.com')),
                   ('2020-12-08 19:00:00', 18, 7, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 3 - STREET 14') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Shawshank Redemption') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'bernard@email.com')),
                   ('2020-12-08 19:00:00', 9, 9, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 3 - STREET 14') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Shawshank Redemption') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'faith.p@email.com')),
                   ('2020-12-08 19:00:00', 12, 18, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 3 - STREET 14') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Shawshank Redemption') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'johnnie@email.com')),
                   ('2020-12-08 19:00:00', 11, 5, (SELECT movie_cinema_id FROM movie_cinema WHERE cinema_id = (SELECT c.cinema_id FROM cinema c WHERE c.name = 'Hall 3 - STREET 14') AND movie_id = (SELECT m.movie_id FROM movie m WHERE m.name = 'The Shawshank Redemption') LIMIT 1), (SELECT user_account_id from user_account WHERE email = 'lawrence.f@email.com'));
